In [7]:
from sklearn.datasets import fetch_20newsgroups
twenty_train = fetch_20newsgroups(subset='train', shuffle=True)

In [3]:
# You can check the target names (categories) and some data files by following commands.
twenty_train.target_names #prints all the categories


['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [5]:
import json

def common_entries(*dcts):
    for i in set(dcts[0]).intersection(*dcts[1:]):
        yield (i,) + tuple(d[i] for d in dcts)


data = None
with open('ex.txt') as f:
    data = json.load(f)
user_data = data['user_tweets']
main_data = data['article_pooltweets']

text_data = list()
url_data = list()

for i in main_data:
    text_data.append(i['person_tweets'])
    url_data.append(i['article_url'])

result = (user_data,(text_data,url_data))
print(url_data)


<class 'dict'>
['https://nbcnews.to/2Dyx8Lq', 'https://nbcnews.to/2Dyx8Lq', 'https://nbcnews.to/2Dyx8Lq', 'https://nbcnews.to/2Dyx8Lq', 'https://nbcnews.to/2Dyx8Lq', 'https://nbcnews.to/2Dyx8Lq', 'https://nbcnews.to/2Dyx8Lq', 'https://nbcnews.to/2Dyx8Lq', 'https://nbcnews.to/2Dyx8Lq', 'https://nbcnews.to/2Dyx8Lq', 'https://cnn.it/2QErLNK', 'https://cnn.it/2QErLNK', 'https://cnn.it/2QErLNK', 'https://cnn.it/2QErLNK', 'https://cnn.it/2QErLNK', 'https://cnn.it/2QErLNK', 'https://cnn.it/2QErLNK', 'https://cnn.it/2QErLNK', 'https://cnn.it/2QErLNK', 'https://cnn.it/2QErLNK', 'http://usatoday.com/story/news/politics/onpolitics/2018/11/12/richard-ojeda-2020-presidential-candidate/1977818002/', 'http://usatoday.com/story/news/politics/onpolitics/2018/11/12/richard-ojeda-2020-presidential-candidate/1977818002/', 'http://usatoday.com/story/news/politics/onpolitics/2018/11/12/richard-ojeda-2020-presidential-candidate/1977818002/', 'http://usatoday.com/story/news/politics/onpolitics/2018/11/12/rich

In [9]:
print(type(twenty_train.data[0]))

<class 'str'>


In [12]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
#from sklearn import neighbors, datasets
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.neighbors import NearestNeighbors

num_neighbors = 6
# y = twenty_train.target

count_vect = CountVectorizer()
tfidf_transformer = TfidfTransformer()


data = ""


X_train_counts = count_vect.fit_transform(twenty_train.data)
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X = X_train_tfidf


# ['auto', 'ball_tree', 'kd_tree', 'brute']
clf = NearestNeighbors(num_neighbors, algorithm='auto').fit(X)

user_data = ""

distances, indices = clf.kneighbors(X[0])
print(clf.kneighbors_graph(X).toarray())
print(indices)
print(distances)

matches = list()
for i,j in zip(twenty_train.data, indices[0]):
    print(type(j))
    if j == 1:
        matches.append(i)

print(matches)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
[[    0   958 10576  3277  8266  3678]]
[[0.         0.94902109 1.15842826 1.19784914 1.21034824 1.21037728]]
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
[]


In [75]:
def sort_list(list1, list2): 
  
    zipped_pairs = zip(list2, list1) 
  
    z = [x for _, x in sorted(zipped_pairs)] 
      
    return z 

temp1 = indices[0]
temp2 = distances[0]


print(temp1.tolist())
print(temp2.tolist())
print(sort_list(temp1,temp2))






[0, 958, 10576, 3277, 8266, 3678]
[0.0, 0.9490210871229312, 1.1584282600930755, 1.1978491430929878, 1.210348243511742, 1.2103772820800736]
[0, 958, 10576, 3277, 8266, 3678]
[[0.         0.94902109 1.15842826 1.19784914 1.21034824 1.21037728]]
[[1.         3.7986832  4.65881255 4.83054086 4.88563936 4.88576773]]
